name: ui_kit
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.4 <4.0.0"
  flutter: ">=3.38.5 <4.0.0"

dependencies:
  dependencies:
    path: ../../shared/dependencies
  flutter:
    sdk: flutter
  flutter_spinkit: 5.2.2
  flutter_svg: 2.2.3
  google_fonts: 8.0.1
  lottie: 3.3.2
  vector_graphics: 1.1.19

dev_dependencies:
  build_runner: 2.11.1
  flutter_test:
    sdk: flutter
  very_good_analysis: 10.1.0

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true
