name: dependencies
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.10.4 <4.0.0"
  flutter: ">=3.38.5 <4.0.0"

dependencies:
  auto_route: 11.1.0
  bloc: 9.2.0
  collection: 1.19.1
  dartz: 0.10.1
  dio: 5.9.1
  envied: 1.3.2
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  flutter_localization: 0.3.3
  freezed_annotation: 3.1.0
  intl: 0.20.2
  reactive_forms: 18.2.2
  retrofit: 4.9.2
  rxdart: 0.28.0
  shared_preferences: 2.5.4
  talker_bloc_logger: 5.1.13
  talker_dio_logger: 5.1.13
  talker_flutter: 5.1.13
  theme_tailor_annotation: 3.1.2
  url_strategy: 0.3.0
  yx_scope: 1.2.0
  yx_scope_flutter: 1.2.0

dev_dependencies:
  build_runner: 2.11.1
  flutter_test:
    sdk: flutter
  very_good_analysis: 10.1.0
