name: base_app_services
description: "Базовые сервисы для приложения"
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Зависимости для сервиса защищенного хранилища
  flutter_secure_storage: 9.2.4

  # Зависимости для сервиса незащищенного хранилища
  shared_preferences: 2.5.4

  # для работы с путями в хранилища
  path_provider: 2.1.5

  # Работа с геолокацией
  geolocator: 14.0.2

  # Обязательные интерфейсы
  i_app_services:
    path: ../../i_app_services

dev_dependencies:
  flutter_lints: 6.0.0
