name: app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.10.4

dependencies:
  auth:
    path: ../../modules/auth
  base_app_services:
    path: ../../app_services/base/app_services
  core:
    path: ../../shared/core
  dependencies:
    path: ../../shared/dependencies
  flutter:
    sdk: flutter

dev_dependencies:
  auto_route_generator: 10.4.0
  build_runner: 2.11.1
  envied_generator: 1.3.2
  flutter_flavorizr: 2.4.1
  flutter_launcher_icons: 0.14.4
  flutter_test:
    sdk: flutter
  freezed: 3.2.5
  json_serializable: 6.12.0
  very_good_analysis: 10.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/launcher_icon/
flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true
